// AUTO-GENERATED by scripts/parse-prices.ts — do not edit manually
// Run `pnpm scrape:prices` after placing source data in ../research/prices/all_prices.json

export interface PriceItem { id: string; name: string; price: number | null; unit?: string; featured?: boolean; }
export interface PriceCategory { id: string; name: string; items: PriceItem[]; }
export const priceCategories: PriceCategory[] = [];
export const featuredPrices: PriceItem[] = [];
