// AUTO-GENERATED by scripts/parse-reviews.ts — do not edit manually
// Run `pnpm scrape:reviews` after placing source data in ../research/reviews_yandex.json

export type ReviewSource = 'yandex';

export interface Review {
  id: string;
  author: string;
  date: string;
  rating: 5;
  text: string;
  source: ReviewSource;
}

export const reviews: Review[] = [];
