/**
 * Reads ../research/reviews_yandex.json (100 reviews) and writes content/reviews.ts.
 * Selects top-12 five-star reviews scored by (text_length * recency_weight).
 * Run: pnpm scrape:reviews
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface RawReview {
  author: string;
  date: string;    // ISO date string e.g. '2025-11-20T...'
  rating: string;  // '5.0', '4.0', '1.0', etc.
  text?: string;
  body?: string;   // some scrapers use 'body' instead of 'text'
}

interface RawRoot {
  unique?: number;
  reviews: RawReview[];
}

interface Review {
  id: string;
  author: string;
  date: string;
  rating: 5;
  text: string;
  source: 'yandex';
}

const MAX_TEXT = 280;
const MIN_TEXT = 150;
const TOP_N = 12;

function recencyWeight(dateStr: string): number {
  const monthsOld =
    (Date.now() - new Date(dateStr).getTime()) / (1000 * 60 * 60 * 24 * 30);
  if (monthsOld <= 12) return 2.0;
  if (monthsOld <= 24) return 1.5;
  return 1.0;
}

function scoreReview(r: RawReview): number {
  const text = r.text ?? r.body ?? '';
  return text.length * recencyWeight(r.date);
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return text.slice(0, max).trimEnd() + '…';
}

function main(): void {
  const inputPath = path.resolve(__dirname, '../../research/reviews_yandex.json');
  const outputPath = path.resolve(__dirname, '../content/reviews.ts');

  if (!fs.existsSync(inputPath)) {
    console.error(`Input not found: ${inputPath}`);
    process.exit(1);
  }

  const parsed = JSON.parse(
    fs.readFileSync(inputPath, 'utf-8')
  ) as RawRoot | RawReview[];

  // Support both { unique, reviews: [...] } and plain array formats
  const rawList: RawReview[] = Array.isArray(parsed) ? parsed : parsed.reviews;

  // Dedupe by author+date, keep 5-star only, min text length
  const seen = new Set<string>();
  const filtered = rawList.filter(r => {
    const text = r.text ?? r.body ?? '';
    if (r.rating !== '5.0' && r.rating !== '5') return false;
    if (text.length < MIN_TEXT) return false;
    const key = `${r.author}|${r.date}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  const top = [...filtered]
    .sort((a, b) => scoreReview(b) - scoreReview(a))
    .slice(0, TOP_N);

  console.log(
    `Selected ${top.length} reviews from ${rawList.length} total (filtered pool: ${filtered.length})`
  );

  const reviews: Review[] = top.map((r, i) => ({
    id: `review-${String(i + 1).padStart(2, '0')}`,
    author: r.author,
    date: r.date,
    rating: 5,
    text: truncate(r.text ?? r.body ?? '', MAX_TEXT),
    source: 'yandex',
  }));

  const output = [
    '// AUTO-GENERATED by scripts/parse-reviews.ts — do not edit manually',
    '',
    "export type ReviewSource = 'yandex';",
    '',
    'export interface Review {',
    '  id: string;',
    '  author: string;',
    '  date: string;',
    '  rating: 5;',
    '  text: string;',
    '  source: ReviewSource;',
    '}',
    '',
    `export const reviews: Review[] = ${JSON.stringify(reviews, null, 2)};`,
  ].join('\n');

  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log(`Written: ${outputPath}`);
}

main();
